### ISSUE TITLE
Mosquitto Integration

### ISSUE THREAD

**Issue by elusiveplanet** [bearbotics2358/Endeavor#1]
Mosquitto is not yet properly integrated into the robot project. It's an Eclipse issue. (or maybe not?) Use this thread to document what you try/do, successful or unsuccessful.

**Comment by bobd13** [comment]
Please see gunar_mosquitto branch,  and email explanation from last night.  It works now.

**Comment by elusiveplanet** [comment]
Runs well on my machine. Closing issue. (unless it decides to scream at us again)
